---


- name: Actualizar la caché de paquetes de apt
  ansible.builtin.apt:
    update_cache: true

- name: Instalar dependencias previas
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - lsb-release
    state: present

- name: Descargar el paquete oficial de Percona
  ansible.builtin.get_url:
    url: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    dest: /tmp/percona-release_latest.generic_all.deb
    mode: '0644'

- name: Instalar el paquete de configuración de repositorios
  ansible.builtin.apt:
    deb: /tmp/percona-release_latest.generic_all.deb

- name: Configurar Percona Server 8.4 LTS
  ansible.builtin.command: percona-release setup ps-84-lts --scheme https
  register: percona_setup
  changed_when: "'Ready' in percona_setup.stdout"

# Ubuntu 26.04 (resolute) aún no tiene paquetes compilados en Percona
# Voy a usar el repo de la version noble (24.04) que es compatible
- name: Reemplazar resolute por noble en el repo de Percona
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '\bresolute\b'
    replace: 'noble'
  loop:
    - /etc/apt/sources.list.d/percona-ps-84-lts-release.list
    - /etc/apt/sources.list.d/percona-ps-84-lts-release.list.bak

- name: Forzar actualización de caché de apt
  ansible.builtin.apt:
    update_cache: true

- name: Instalar Percona Server
  ansible.builtin.apt:
    name: percona-server-server
    state: present

- name: Asegurar que el servicio de MySQL esté iniciado y activo (systemd)
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true

- name: Copiar configuración personalizada de my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar MySQL

- name: Instalar extensiones de Python para gestionar MySQL
  ansible.builtin.apt:
    name:
      - python3-pymysql
    state: present


- name: Establecer contraseña para el usuario root
  ansible.builtin.command: >
    mysql -u root -S /var/run/mysqld/mysqld.sock -e
    "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
  no_log: true
  changed_when: true

- name: Crear usuario ansible_test_user con permisos de solo lectura
  ansible.builtin.command: >
    mysql -u root -S /var/run/mysqld/mysqld.sock -e
    "CREATE USER IF NOT EXISTS 'ansible_test_user'@'%' IDENTIFIED BY '{{ ansible_test_password }}';
     GRANT SELECT ON *.* TO 'ansible_test_user'@'%';
     FLUSH PRIVILEGES;"
  no_log: true
  changed_when: true